apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: telegraf
  name: telegraf
spec:
  selector:
    matchLabels:
      app: telegraf 
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
        - name: telegraf
          image: telegraf:latest
          volumeMounts:
            - mountPath: /etc/telegraf
              name: config 
              readOnly: true
      volumes:
      - name: config 
        configMap:
          name: telegraf-config 
